package plugin

import "text/template"

var headerTemplate = template.Must(template.New("header").Parse(`
// Code generated by protoc-gen-go-gorm. DO NOT EDIT.
// source: {{ .Proto.Name }}

package {{ .GoPackageName }}

// cockroachdb doesn't support nanosecond timestamp columns so use microsecond instead
const TimestampFormat = "2006-01-02T15:04:05.999999Z07:00"
`))
