name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'example/**'
      - 'options/**'
      - 'plugin/**'
      - 'proto/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    if: github.event.pull_request.draft == false
    name: Make a Release
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - uses: actions/checkout@v3
      - name: Setup Go With Caching
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"
      - name: Get semver-tags
        run: |
          go install github.com/catalystsquad/semver-tags@latest
      - name: Release
        id: semver-tags
        run: |
          ./.github/scripts/do_release.sh fullrun